[package]
name = "intcode-jit"
version = "0.1.0"
authors = ["Paul Emmerich <paul.emmerich@croit.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dynasm = "0.5.2"
dynasmrt = "0.5.2"
